version: '3.8'

services:
  app:
    build: .
    container_name: express_app
    ports:
      - '3100:3100'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
